name: talkpal
description: A new flutter package project.
version: 0.0.1
author:
homepage:

dependencies:

  built_value: ^5.4.3
  built_collection: ^3.1.1
  built_redux: 7.4.1-dev
  built_redux_rx: "^0.1.1"


dev_dependencies:
  test: ^0.12.30
  built_value_generator: ^5.4.3
  build_runner: ^0.8.2
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
